In [1]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [2]:
import numpy as np

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
voc_size = 10000

In [5]:
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[4251, 2121, 6228, 7280],
 [4251, 2121, 6228, 910],
 [4251, 9087, 6228, 5982],
 [9338, 9057, 996, 3841, 4896],
 [9338, 9057, 996, 3841, 7790],
 [3067, 4251, 165, 6228, 7217],
 [1079, 3745, 7465, 3841]]

In [6]:
sen_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding = 'pre', maxlen = sen_length)
print(embedded_docs)

[[   0    0    0    0 4251 2121 6228 7280]
 [   0    0    0    0 4251 2121 6228  910]
 [   0    0    0    0 4251 9087 6228 5982]
 [   0    0    0 9338 9057  996 3841 4896]
 [   0    0    0 9338 9057  996 3841 7790]
 [   0    0    0 3067 4251  165 6228 7217]
 [   0    0    0    0 1079 3745 7465 3841]]


In [7]:
dim = 10

In [8]:
model = Sequential()
model.add(Embedding(voc_size, dim))
model.compile('adam', 'mse')

In [9]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step


array([[[-0.01472905, -0.00154524, -0.00851507, -0.03855072,
         -0.01597615, -0.04435282, -0.0321425 ,  0.04151465,
          0.04431847, -0.02648176],
        [-0.01472905, -0.00154524, -0.00851507, -0.03855072,
         -0.01597615, -0.04435282, -0.0321425 ,  0.04151465,
          0.04431847, -0.02648176],
        [-0.01472905, -0.00154524, -0.00851507, -0.03855072,
         -0.01597615, -0.04435282, -0.0321425 ,  0.04151465,
          0.04431847, -0.02648176],
        [-0.01472905, -0.00154524, -0.00851507, -0.03855072,
         -0.01597615, -0.04435282, -0.0321425 ,  0.04151465,
          0.04431847, -0.02648176],
        [ 0.02236615,  0.04116383, -0.02601191,  0.02803235,
          0.03390285,  0.03662986, -0.02543581,  0.00648482,
          0.02939672, -0.02291981],
        [ 0.0160931 ,  0.00501521,  0.0139575 , -0.03123075,
         -0.00160706,  0.03891948,  0.04417502, -0.0439139 ,
         -0.00535572,  0.04217526],
        [-0.04192592, -0.03936535, -0.03020939,  0.0

In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [12]:
embedded_docs[0]

array([   0,    0,    0,    0, 4251, 2121, 6228, 7280])

In [17]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step


array([[-0.01472905, -0.00154524, -0.00851507, -0.03855072, -0.01597615,
        -0.04435282, -0.0321425 ,  0.04151465,  0.04431847, -0.02648176],
       [-0.01472905, -0.00154524, -0.00851507, -0.03855072, -0.01597615,
        -0.04435282, -0.0321425 ,  0.04151465,  0.04431847, -0.02648176],
       [-0.01472905, -0.00154524, -0.00851507, -0.03855072, -0.01597615,
        -0.04435282, -0.0321425 ,  0.04151465,  0.04431847, -0.02648176],
       [-0.01472905, -0.00154524, -0.00851507, -0.03855072, -0.01597615,
        -0.04435282, -0.0321425 ,  0.04151465,  0.04431847, -0.02648176],
       [ 0.02236615,  0.04116383, -0.02601191,  0.02803235,  0.03390285,
         0.03662986, -0.02543581,  0.00648482,  0.02939672, -0.02291981],
       [ 0.0160931 ,  0.00501521,  0.0139575 , -0.03123075, -0.00160706,
         0.03891948,  0.04417502, -0.0439139 , -0.00535572,  0.04217526],
       [-0.04192592, -0.03936535, -0.03020939,  0.03987281, -0.03071344,
        -0.03646574,  0.04577521,  0.04062135